name: Discord - Styled Releases/Patch Notes
description: Send automatic styled releases to Discord.
inputs:
  webhook_id:
    description: Discord's webhook id. Use GH repo secrets.
    required: true
  webhook_token:
    description: Discord's webhook token. Use GH repo secrets.
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
branding:
  color: orange
  icon: radio